### ISSUE TITLE
Is crocoite Linux-only?

### ISSUE THREAD

**Issue by janpieterk** [PromyLOPh/crocoite#27]
Dear developers, it seems to me that the binary `google-chrome-stable` is hardcoded in crocoite and I believe that binary does not exist on macOS. I installed the Homebrew package `chrome-cli` and symlinked `google-chrome-stable` to `chrome-cli`, however, crocoite still won't run on my Mac. ("Exception: Chrome died on us.\n").

Will crocoite run at all on a Mac or is it Linux-only?

Thanks.

**Comment by PromyLOPh** [comment]
Honest answer is: I don’t know if it will run on macOS, because I have
not tested it.

I don’t think chrome-cli is the correct package though. crocoite expects
the binary google-chrome-stable to be the Chrome browser itself.  Not
sure where it’s installed on macOS, but on Gentoo Linux it resides in
/opt/google/chrome/ – this SO question might give you a hint:
https://superuser.com/a/157486

**Comment by janpieterk** [comment]
On macOS the Google Chrome binary resides in `/Applications/Google Chrome.app/Contents/MacOS/Google Chrome`. Symlinking `/usr/local/bin/google-chrome-stable` to there and running crocoite results in the same `"Exception: Chrome died on us.\n"` error.
For now I am assuming that crocoite won't run on macOS, and closing this issue. Thanks for the help!
